version: '3'
services:
  app:
    build: .
    depends_on:
      - dhtspider
      - mongo
    volumes:
      - /dhtspider:/var/dhtspider
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]
  dhtspider:
    image: derekchuank/dhtspider
    ports:
      - "6339:6339/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - /dhtspider:/var/dhtspider
  mongo:
    image: mongo
    restart: always
    volumes:
      - /mongo-data:/data/db
